title: A Kingdom for Kefling
description: An unofficial wiki dedicated to documenting all aspects of A Kingdom for Keflings.
theme: just-the-docs
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: dark

url: https://kuruvt.github.io/akfk

aux_links:
  Official Website: https://www.ninjabee.com/games/akingdomforkeflings/
  Official Discord: https://discord.gg/R9d95zQpJH

footer_content: "An unofficial wiki for A Kingdom for Keflings."
last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" 

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/KuruVT/akfk"
gh_edit_branch: "main" 
gh_edit_view_mode: "edit"

callouts:
  highlight:
    title: Highlight
    color: grey-lt
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

collections:
  giants:
    permalink: "/giants/:title/"
    output: true

just_the_docs:
  show_last_modified_at: true 
  collections:
    giants:
      name: giants
      nav_fold: true 

